import { execFileSync } from "child_process";
import {
  existsSync,
  lstatSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
} from "fs";
import { tmpdir } from "os";
import { join, resolve } from "path";
import { afterEach, describe, expect, it } from "vitest";

const ROOT = resolve(__dirname, "..");
const INSTALLER = join(ROOT, "scripts/install.sh");

const tempHomes: string[] = [];

function makeHome(): string {
  // intent: isolate installer smoke tests from real user config directories
  // status: done
  // next: none
  // blockers: none
  // confidence: high
  const home = mkdtempSync(join(tmpdir(), "ut-install-home-"));
  tempHomes.push(home);
  return home;
}

function runInstall(tier: "oss" | "core", home: string): string {
  return execFileSync("bash", [INSTALLER, `--tier=${tier}`, "--no-pull", "--yes"], {
    cwd: ROOT,
    env: { ...process.env, HOME: home },
    encoding: "utf-8",
    timeout: 30000,
    stdio: ["ignore", "pipe", "pipe"],
  });
}

function expectSymlink(path: string, target: string): void {
  expect(existsSync(path), `${path} should exist`).toBe(true);
  expect(lstatSync(path).isSymbolicLink(), `${path} should be a symlink`).toBe(true);
  expect(realpathSync(path)).toBe(realpathSync(target));
}

afterEach(() => {
  for (const home of tempHomes.splice(0)) {
    rmSync(home, { recursive: true, force: true });
  }
});

describe("install.sh smoke tests", () => {
  it.each(["oss", "core"] as const)(
    "installs %s tier into temporary Claude and Codex homes",
    (tier) => {
      const home = makeHome();
      const output = runInstall(tier, home);

      expect(output).toContain(`UltraThink ${tier.toUpperCase()} installed successfully`);

      expectSymlink(join(home, ".claude/skills/_registry.json"), join(ROOT, ".claude/skills/_registry.json"));
      expectSymlink(join(home, ".claude/references"), join(ROOT, ".claude/references"));
      expectSymlink(join(home, ".claude/agents"), join(ROOT, ".claude/agents"));
      expectSymlink(join(home, ".claude/hooks/ultrathink-privacy-hook.sh"), join(ROOT, ".claude/hooks/privacy-hook.sh"));

      expectSymlink(join(home, ".codex/AGENTS.md"), join(ROOT, "AGENTS.md"));

      const codexConfig = readFileSync(join(home, ".codex/config.toml"), "utf-8");
      const codexHooks = readFileSync(join(home, ".codex/hooks.json"), "utf-8");
      expect(codexConfig).toContain("Generated by UltraThink installer");
      expect(codexConfig).toContain(join(ROOT, "packages/code-intel/dist/index.js"));
      expect(codexConfig).toContain(join(ROOT, "mcp/agora/dist/index.js"));
      expect(codexHooks).toContain(join(ROOT, "scripts/hook-adapter.mjs"));

      const config = JSON.parse(readFileSync(join(home, ".ultrathink/config.json"), "utf-8"));
      expect(config.tier).toBe(tier);
      expect(config.source_repo).toBe(ROOT);
      expect(config.vault_path).toBe(join(home, ".ultrathink/vault"));

      expect(existsSync(join(home, ".ultrathink/vault/memories"))).toBe(true);
      expect(existsSync(join(home, ".ultrathink/vault/decisions"))).toBe(true);
    }
  );

  it("keeps core-only Claude paths out of OSS installs", () => {
    const home = makeHome();
    runInstall("oss", home);

    expect(existsSync(join(home, ".ultrathink/vault/identity"))).toBe(false);
    expect(existsSync(join(home, ".claude/hooks/ultrathink-codeintel-session-check.sh"))).toBe(false);
    expect(existsSync(join(home, ".claude/hooks/ultrathink-decision-inject.sh"))).toBe(false);
  });

  it("includes core-only Claude paths in Core installs", () => {
    const home = makeHome();
    runInstall("core", home);

    expect(existsSync(join(home, ".ultrathink/vault/identity"))).toBe(true);
    expectSymlink(
      join(home, ".claude/hooks/ultrathink-codeintel-session-check.sh"),
      join(ROOT, ".claude/hooks/codeintel-session-check.sh")
    );
    expectSymlink(
      join(home, ".claude/hooks/ultrathink-decision-inject.sh"),
      join(ROOT, ".claude/hooks/decision-inject.sh")
    );
  });
});
