#!/usr/bin/env bash
# intent: UltraThink Core installer — auto-detect, auto-pull, unified runner setup
# status: done
# next: keep Claude, Codex, and OpenAI-compatible template installs in one path
# blockers: none
# confidence: high
set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ULTRA_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly CLAUDE_DIR="$HOME/.claude"
readonly CODEX_DIR="$HOME/.codex"
readonly ULTRA_DATA="$HOME/.ultrathink"
readonly RUNNER_TEMPLATES_DIR="$ULTRA_DATA/runners/templates"
readonly VERSION="3.0.0"

readonly RED='\033[0;31m'   GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m' BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'   BOLD='\033[1m'
readonly NC='\033[0m'

# ── Logging ──
log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_step()  { echo -e "\n${CYAN}${BOLD}[$1/$TOTAL_STEPS]${NC} $2"; }
log_dry()   { echo -e "${YELLOW}[DRY]${NC}  $*"; }

TOTAL_STEPS=8

# ── Dry-run helpers ──
run_cmd() {
  if $DRY_RUN; then log_dry "would run: $*"; else "$@"; fi
}
dry_ln() {
  if $DRY_RUN; then log_dry "ln -sfn $1 -> $2"; else ln -sfn "$1" "$2"; fi
}
dry_mkdir() {
  if $DRY_RUN; then log_dry "mkdir -p $*"; else mkdir -p "$@"; fi
}
dry_rm() {
  if $DRY_RUN; then log_dry "rm $*"; else rm "$@"; fi
}
link_file_with_backup() {
  local src="$1"
  local dest="$2"
  [[ -f "$src" ]] || return 0
  if [[ -e "$dest" && ! -L "$dest" ]]; then
    run_cmd mv "$dest" "$dest.bak.$(date +%s)"
  fi
  dry_ln "$src" "$dest"
}
render_codex_file() {
  local src="$1"
  local dest="$2"
  local kind="$3"
  [[ -f "$src" ]] || return 0

  if $DRY_RUN; then
    log_dry "render $src -> $dest"
    return 0
  fi

  if [[ -L "$dest" ]]; then
    rm "$dest"
  elif [[ -e "$dest" ]] && ! grep -q "$ULTRA_ROOT" "$dest" 2>/dev/null; then
    mv "$dest" "$dest.bak.$(date +%s)"
  fi

  node - "$src" "$dest" "$ULTRA_ROOT" "$kind" <<'NODE'
const fs = require('node:fs');
const path = require('node:path');

const [src, dest, root, kind] = process.argv.slice(2);
let content = fs.readFileSync(src, 'utf8');

if (kind === 'config') {
  const abs = (relativePath) => JSON.stringify(path.join(root, relativePath));
  content = content
    .replace('args = ["packages/code-intel/dist/index.js"]', `args = [${abs('packages/code-intel/dist/index.js')}]`)
    .replace('args = ["mcp/agora/dist/index.js"]', `args = [${abs('mcp/agora/dist/index.js')}]`);
  content = `# Generated by UltraThink installer from .codex/config.toml.\n# Edit the repo template or rerun install.sh instead of hand-editing this file.\n${content}`;
} else if (kind === 'hooks') {
  content = content.replaceAll('node scripts/hook-adapter.mjs', `node ${path.join(root, 'scripts/hook-adapter.mjs')}`);
}

fs.writeFileSync(dest, content.endsWith('\n') ? content : `${content}\n`);
NODE
}

# ── Auto-detect tier from repo structure ──
auto_detect_tier() {
  if [[ -f "$ULTRA_ROOT/scripts/upgrade-to-builder.sh" ]]; then
    echo "core"
  else
    echo "oss"
  fi
}

# ── Parse args ──
TIER=""
DB_URL=""
VAULT_PATH="$ULTRA_DATA/vault"
UNINSTALL=false
UPDATE=false
DRY_RUN=false
NO_IDENTITY=false
NO_RUNNERS=false
NO_PULL=false
AUTO_YES=false

for arg in "$@"; do
  case "$arg" in
    --tier=*)       TIER="${arg#*=}" ;;
    --db=*)         DB_URL="${arg#*=}" ;;
    --vault=*)      VAULT_PATH="${arg#*=}" ;;
    --uninstall)    UNINSTALL=true ;;
    --update)       UPDATE=true ;;
    --dry-run)      DRY_RUN=true ;;
    --no-identity)  NO_IDENTITY=true ;;
    --no-runners)   NO_RUNNERS=true ;;
    --no-pull)      NO_PULL=true ;;
    --yes|-y)       AUTO_YES=true ;;
    --help|-h)
      echo "Usage: install.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --tier=oss|core   Installation tier (auto-detected if omitted)"
      echo "  --db=URL          Neon Postgres connection string"
      echo "  --vault=PATH      Obsidian vault location (default: ~/.ultrathink/vault)"
      echo "  --no-identity     Skip adding UltraThink section to ~/.claude/CLAUDE.md"
      echo "  --no-runners      Skip linking Codex/OpenAI-compatible runner files"
      echo "  --no-pull         Skip auto-pull even if git repo is behind"
      echo "  --yes, -y         Auto-approve all prompts"
      echo "  --dry-run         Print what would be changed without modifying anything"
      echo "  --update          Pull latest changes and re-install"
      echo "  --uninstall       Remove UltraThink from ~/.claude/ and ~/.ultrathink/"
      echo "  --help, -h        Show this help"
      exit 0 ;;
    *)
      log_warn "Unknown option: $arg (ignored)" ;;
  esac
done

if $DRY_RUN; then
  echo ""
  log_warn "DRY RUN — no files will be modified"
fi

# ════════════════════════════════════════════════════════════════════════════
# ── UNINSTALL ──
# ════════════════════════════════════════════════════════════════════════════
if $UNINSTALL; then
  echo ""
  log_info "Uninstalling UltraThink..."
  REMOVED=()

  # 1. Remove skill symlinks
  for link in "$CLAUDE_DIR/skills"/*/; do
    name="$(basename "$link")"
    if [[ -L "$CLAUDE_DIR/skills/$name" ]]; then
      dry_rm "$CLAUDE_DIR/skills/$name"
      REMOVED+=("skill: $name")
    fi
  done
  if [[ -L "$CLAUDE_DIR/skills/_registry.json" ]]; then
    dry_rm "$CLAUDE_DIR/skills/_registry.json"
    REMOVED+=("skills/_registry.json")
  fi

  # 2. Remove references + agents symlinks
  if [[ -L "$CLAUDE_DIR/references" ]]; then
    dry_rm "$CLAUDE_DIR/references"
    REMOVED+=("references/ symlink")
  fi
  if [[ -L "$CLAUDE_DIR/agents" ]]; then
    dry_rm "$CLAUDE_DIR/agents"
    REMOVED+=("agents/ symlink")
  fi

  # 3. Remove hook symlinks
  for hook in "$CLAUDE_DIR/hooks"/ultrathink-*; do
    if [[ -L "$hook" ]]; then
      dry_rm "$hook"
      REMOVED+=("hook: $(basename "$hook")")
    fi
  done

  # 4. Remove UltraThink section from CLAUDE.md
  CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
  if [[ -f "$CLAUDE_MD" ]] && grep -q "## UltraThink Integration" "$CLAUDE_MD" 2>/dev/null; then
    if $DRY_RUN; then
      log_dry "would remove UltraThink section from $CLAUDE_MD"
    else
      {
        in_ut_block=false
        found_separator=false
        separator_line=""
        while IFS= read -r line; do
          if [[ "$line" == "---" ]] && ! $in_ut_block; then
            separator_line="$line"
            found_separator=true
            continue
          fi
          if $found_separator; then
            if [[ -z "$line" ]]; then
              separator_line="${separator_line}"$'\n'"$line"
              continue
            elif [[ "$line" =~ ^"## UltraThink Integration" ]]; then
              in_ut_block=true
              found_separator=false
              separator_line=""
              continue
            else
              echo "$separator_line"
              echo "$line"
              found_separator=false
              separator_line=""
              continue
            fi
          fi
          if $in_ut_block; then
            if [[ "$line" =~ ^"## " ]] || [[ "$line" == "---" ]]; then
              in_ut_block=false
              echo "$line"
            fi
            continue
          fi
          echo "$line"
        done < "$CLAUDE_MD"
      } > "$CLAUDE_MD.clean"
      mv "$CLAUDE_MD.clean" "$CLAUDE_MD"
    fi
    REMOVED+=("UltraThink section from CLAUDE.md")
  fi

  # 5. Remove UltraThink hook entries from settings.json
  SETTINGS="$CLAUDE_DIR/settings.json"
  if [[ -f "$SETTINGS" ]] && grep -q "ultrathink-" "$SETTINGS" 2>/dev/null; then
    if $DRY_RUN; then
      log_dry "would remove UltraThink hooks from $SETTINGS"
    else
      cat > /tmp/ut-clean-hooks.js << 'CLEANJS'
const fs = require('fs');
const p = process.argv[2];
const s = JSON.parse(fs.readFileSync(p, 'utf-8'));
if (s.hooks) {
  for (const event of Object.keys(s.hooks)) {
    s.hooks[event] = (s.hooks[event] || []).filter(entry => {
      if (entry.id && entry.id.startsWith('ut:')) return false;
      const cmds = (entry.hooks || []).map(h => h.command || '');
      return !cmds.some(c => c.includes('ultrathink-'));
    });
    if (s.hooks[event].length === 0) delete s.hooks[event];
  }
  if (Object.keys(s.hooks).length === 0) delete s.hooks;
}
fs.writeFileSync(p, JSON.stringify(s, null, 2) + '\n');
CLEANJS
      node /tmp/ut-clean-hooks.js "$SETTINGS" 2>/dev/null && true
      rm -f /tmp/ut-clean-hooks.js
    fi
    REMOVED+=("UltraThink hooks from settings.json")
  fi

  # 6. Remove Codex/OpenAI-compatible runner files
  for file in "$CODEX_DIR/config.toml" "$CODEX_DIR/hooks.json"; do
    if [[ -L "$file" ]]; then
      dry_rm "$file"
      REMOVED+=("runner link: $file")
    elif [[ -f "$file" ]] && grep -q "$ULTRA_ROOT" "$file" 2>/dev/null; then
      dry_rm "$file"
      REMOVED+=("generated runner file: $file")
    fi
  done
  for link in "$CODEX_DIR/AGENTS.md" "$RUNNER_TEMPLATES_DIR/AGENTS.md" "$RUNNER_TEMPLATES_DIR/CLAUDE.md"; do
    if [[ -L "$link" ]]; then
      dry_rm "$link"
      REMOVED+=("runner link: $link")
    fi
  done

  # 7. Remove ~/.ultrathink/ (with confirmation)
  if [[ -d "$ULTRA_DATA" ]]; then
    if $DRY_RUN; then
      log_dry "would prompt to remove $ULTRA_DATA"
    elif $AUTO_YES; then
      rm -rf "$ULTRA_DATA"
      REMOVED+=("~/.ultrathink/ directory")
    else
      echo ""
      echo -en "  Remove ${BOLD}~/.ultrathink/${NC} (vault, config, decisions)? ${RED}This is irreversible.${NC} [y/N] "
      read -r confirm
      if [[ "$confirm" =~ ^[Yy]$ ]]; then
        rm -rf "$ULTRA_DATA"
        REMOVED+=("~/.ultrathink/ directory")
      else
        log_info "Kept ~/.ultrathink/"
      fi
    fi
  fi

  echo ""
  if [[ ${#REMOVED[@]} -gt 0 ]]; then
    log_ok "Removed ${#REMOVED[@]} items:"
    for item in "${REMOVED[@]}"; do echo "    - $item"; done
  else
    log_info "Nothing to remove"
  fi
  echo ""
  exit 0
fi

# ════════════════════════════════════════════════════════════════════════════
# ── INSTALL / UPDATE ──
# ════════════════════════════════════════════════════════════════════════════

# Auto-detect tier if not specified
if [[ -z "$TIER" ]]; then
  TIER="$(auto_detect_tier)"
  log_info "Auto-detected tier: ${BOLD}$TIER${NC}"
fi

# Validate tier
case "$TIER" in
  oss|core) ;;
  *)
    log_error "Invalid tier: $TIER (must be oss or core)"
    exit 1 ;;
esac

TIER_UPPER=$(echo "$TIER" | tr '[:lower:]' '[:upper:]')

if $UPDATE; then
  echo ""
  log_info "Updating UltraThink ${BOLD}${TIER_UPPER}${NC}..."
fi

echo ""
log_info "Installing UltraThink ${BOLD}${TIER_UPPER}${NC}"
log_info "Source: $ULTRA_ROOT"

# ── Step 1: Auto-pull ──
log_step 1 "Checking for updates"

PULLED=false
if [[ -d "$ULTRA_ROOT/.git" ]] && command -v git &>/dev/null && ! $NO_PULL; then
  cd "$ULTRA_ROOT"
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

  if [[ -n "$CURRENT_BRANCH" ]]; then
    if $DRY_RUN; then
      log_dry "would run: git fetch origin $CURRENT_BRANCH"
    else
      git fetch origin "$CURRENT_BRANCH" 2>/dev/null || true
    fi

    LOCAL=$(git rev-parse HEAD 2>/dev/null || echo "")
    REMOTE=$(git rev-parse "origin/$CURRENT_BRANCH" 2>/dev/null || echo "")

    if [[ -n "$LOCAL" && -n "$REMOTE" && "$LOCAL" != "$REMOTE" ]]; then
      BEHIND=$(git rev-list --count HEAD.."origin/$CURRENT_BRANCH" 2>/dev/null || echo "0")
      if [[ "$BEHIND" -gt 0 ]]; then
        if $UPDATE || $AUTO_YES; then
          if $DRY_RUN; then
            log_dry "would run: git pull origin $CURRENT_BRANCH"
          else
            log_info "Pulling $BEHIND new commit(s)..."
            git pull origin "$CURRENT_BRANCH" --ff-only 2>/dev/null && PULLED=true || {
              log_warn "Fast-forward pull failed — you may have local changes"
              log_info "Run 'git pull' manually to resolve, then re-run installer"
            }
          fi
        else
          log_warn "$BEHIND update(s) available — run with --update to pull, or --no-pull to skip"
        fi
      else
        log_ok "Already up to date"
      fi
    else
      log_ok "Already up to date"
    fi
  else
    log_info "Not on a branch — skipping update check"
  fi
else
  if $NO_PULL; then
    log_info "Skipping update check (--no-pull)"
  elif [[ ! -d "$ULTRA_ROOT/.git" ]]; then
    log_info "Not a git repo — skipping update check"
  else
    log_info "git not available — skipping update check"
  fi
fi

if $PULLED; then
  log_ok "Updated to latest"
fi

# ── Step 2: Prerequisites ──
log_step 2 "Checking prerequisites"

if ! command -v claude &>/dev/null && ! command -v claude-code &>/dev/null; then
  log_warn "Claude Code CLI not found — install from https://claude.ai/download"
fi

NODE_V=$(node --version 2>/dev/null | sed 's/v//' || echo "0")
NODE_MAJOR=$(echo "$NODE_V" | cut -d. -f1)
if [[ "$NODE_MAJOR" -lt 18 ]]; then
  log_error "Node.js 18+ required (found: $NODE_V)"
  exit 1
fi
log_ok "Node.js $NODE_V"

if ! command -v jq &>/dev/null; then
  if [[ "$(uname)" == "Darwin" ]]; then
    log_error "jq required — brew install jq"
  else
    log_error "jq required — sudo apt install jq (Debian/Ubuntu) or sudo dnf install jq (Fedora)"
  fi
  exit 1
fi
log_ok "jq available"

# ── Step 2: Create directories ──
log_step 3 "Creating directory structure"

dry_mkdir "$CLAUDE_DIR/skills" "$CLAUDE_DIR/hooks" "$CODEX_DIR" "$RUNNER_TEMPLATES_DIR"
dry_mkdir "$ULTRA_DATA/forge/projects" "$ULTRA_DATA/decisions/projects"
dry_mkdir "$VAULT_PATH/memories" "$VAULT_PATH/decisions" "$VAULT_PATH/_templates"

if [[ "$TIER" == "core" ]]; then
  dry_mkdir "$VAULT_PATH/identity" "$VAULT_PATH/forge" "$VAULT_PATH/adaptations"
fi

log_ok "~/.claude/, ~/.codex/, and ~/.ultrathink/ ready"

# ── Step 3: Symlink skills ──
log_step 4 "Linking skills"

skill_count=0
for skill_dir in "$ULTRA_ROOT/.claude/skills"/*/; do
  skill_name="$(basename "$skill_dir")"
  target="$CLAUDE_DIR/skills/$skill_name"
  if [[ -d "$target" && ! -L "$target" ]]; then
    log_warn "Skipping skill '$skill_name' — existing directory"
    continue
  fi
  dry_ln "$skill_dir" "$target"
  skill_count=$((skill_count+1))
done
dry_ln "$ULTRA_ROOT/.claude/skills/_registry.json" "$CLAUDE_DIR/skills/_registry.json"
log_ok "Linked $skill_count skills"

# ── Step 4: Symlink references + agents ──
log_step 5 "Linking references and agents"

if [[ -d "$CLAUDE_DIR/references" && ! -L "$CLAUDE_DIR/references" ]]; then
  run_cmd mv "$CLAUDE_DIR/references" "$CLAUDE_DIR/references.bak.$(date +%s)"
fi
dry_ln "$ULTRA_ROOT/.claude/references" "$CLAUDE_DIR/references"
ref_count=$(find "$ULTRA_ROOT/.claude/references/" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
log_ok "Linked $ref_count references"

if [[ -d "$CLAUDE_DIR/agents" && ! -L "$CLAUDE_DIR/agents" ]]; then
  run_cmd mv "$CLAUDE_DIR/agents" "$CLAUDE_DIR/agents.bak.$(date +%s)"
fi
dry_ln "$ULTRA_ROOT/.claude/agents" "$CLAUDE_DIR/agents"
log_ok "Linked agents"

# intent: install Codex and OpenAI-compatible runner templates from repo-owned sources
# status: done
# next: none
# blockers: none
# confidence: high
runner_link_count=0
if $NO_RUNNERS; then
  log_info "Skipping Codex/OpenAI-compatible runner links (--no-runners)"
else
  render_codex_file "$ULTRA_ROOT/.codex/config.toml" "$CODEX_DIR/config.toml" config
  [[ -f "$ULTRA_ROOT/.codex/config.toml" ]] && runner_link_count=$((runner_link_count+1))
  render_codex_file "$ULTRA_ROOT/.codex/hooks.json" "$CODEX_DIR/hooks.json" hooks
  [[ -f "$ULTRA_ROOT/.codex/hooks.json" ]] && runner_link_count=$((runner_link_count+1))
  link_file_with_backup "$ULTRA_ROOT/AGENTS.md" "$CODEX_DIR/AGENTS.md"
  [[ -f "$ULTRA_ROOT/AGENTS.md" ]] && runner_link_count=$((runner_link_count+1))
  link_file_with_backup "$ULTRA_ROOT/AGENTS.md" "$RUNNER_TEMPLATES_DIR/AGENTS.md"
  [[ -f "$ULTRA_ROOT/AGENTS.md" ]] && runner_link_count=$((runner_link_count+1))
  link_file_with_backup "$ULTRA_ROOT/CLAUDE.md" "$RUNNER_TEMPLATES_DIR/CLAUDE.md"
  [[ -f "$ULTRA_ROOT/CLAUDE.md" ]] && runner_link_count=$((runner_link_count+1))
  log_ok "Linked $runner_link_count runner templates/config files"
fi

# ── Step 5: Symlink hooks (tier-aware) ──
log_step 6 "Linking hooks"

# Shared hooks (both tiers)
SHARED_HOOKS="privacy-hook.sh format-check.sh notify.sh memory-auto-save.sh"
SHARED_HOOKS+=" memory-session-start.sh memory-session-end.sh pre-compact.sh"
SHARED_HOOKS+=" prompt-analyzer.ts prompt-submit.sh hook-log.sh statusline.sh"
SHARED_HOOKS+=" suggest-compact.sh context-monitor.sh tool-observe.sh"
SHARED_HOOKS+=" agent-tracker-pre.sh progress-display.sh subagent-verify.sh"
SHARED_HOOKS+=" gsd-utils.sh post-edit-quality.sh registry-sync.sh"
SHARED_HOOKS+=" search-cap.sh vfs-enforce.sh"
SHARED_HOOKS+=" gateguard.sh config-protection.sh batch-quality.sh hook-flags.sh"
SHARED_HOOKS+=" manifest.json"

# Core-only hooks (Tekiō, code-intel, decision engine)
CORE_HOOKS="tool-failure-log.sh codeintel-session-check.sh post-edit-codeintel.sh"
CORE_HOOKS+=" decision-inject.sh forge-hydrate.sh decision-extract.sh"

hook_count=0
IFS=' ' read -ra HOOK_ARR <<< "$SHARED_HOOKS"
for hook in "${HOOK_ARR[@]}"; do
  src="$ULTRA_ROOT/.claude/hooks/$hook"
  [[ -f "$src" ]] || continue
  dry_ln "$src" "$CLAUDE_DIR/hooks/ultrathink-$hook"
  hook_count=$((hook_count+1))
done

if [[ "$TIER" == "core" ]]; then
  IFS=' ' read -ra CORE_ARR <<< "$CORE_HOOKS"
  for hook in "${CORE_ARR[@]}"; do
    src="$ULTRA_ROOT/.claude/hooks/$hook"
    [[ -f "$src" ]] || continue
    dry_ln "$src" "$CLAUDE_DIR/hooks/ultrathink-$hook"
    hook_count=$((hook_count+1))
  done
fi

log_ok "Linked $hook_count hooks"

# ── Step 6: Configure ──
log_step 7 "Writing configuration"

if $DRY_RUN; then
  log_dry "write file: $ULTRA_DATA/config.json"
else
  cat > "$ULTRA_DATA/config.json" << EOF
{
  "tier": "$TIER",
  "version": "$VERSION",
  "installed_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "source_repo": "$ULTRA_ROOT",
  "vault_path": "$VAULT_PATH",
  "database_url": "${DB_URL:-}"
}
EOF
fi
log_ok "Wrote ~/.ultrathink/config.json (tier=$TIER)"

# Write DB URL to .env if provided
if [[ -n "$DB_URL" ]]; then
  if [[ ! -f "$ULTRA_ROOT/.env" ]]; then
    if $DRY_RUN; then
      log_dry "write DATABASE_URL to .env"
    else
      echo "DATABASE_URL=$DB_URL" > "$ULTRA_ROOT/.env"
    fi
    log_ok "Wrote DATABASE_URL to .env"
  fi
fi

# CLAUDE.md — tier-specific identity (opt-in)
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
SKIP_IDENTITY=false

if $NO_IDENTITY; then
  SKIP_IDENTITY=true
  log_info "Skipping CLAUDE.md identity section (--no-identity)"
elif grep -q "UltraThink" "$CLAUDE_MD" 2>/dev/null; then
  SKIP_IDENTITY=true
  log_info "CLAUDE.md already has UltraThink section — skipping"
elif ! $AUTO_YES && ! $DRY_RUN; then
  echo ""
  echo -en "  Add UltraThink identity to ${BOLD}~/.claude/CLAUDE.md${NC}? [y/N] "
  read -r confirm
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    SKIP_IDENTITY=true
    log_info "Skipped CLAUDE.md identity section"
  fi
fi

if ! $SKIP_IDENTITY; then
  if $DRY_RUN; then
    log_dry "would append UltraThink section to $CLAUDE_MD"
  else
    cat >> "$CLAUDE_MD" << EOF

---

## UltraThink Integration ($TIER_UPPER tier)

UltraThink is your active agent harness. Skills in \`~/.claude/skills/<name>/SKILL.md\`.
Registry: \`~/.claude/skills/_registry.json\` ($skill_count skills across 4 layers).
References in \`~/.claude/references/\` — read on demand, not auto-loaded.
Data directory: \`~/.ultrathink/\` (vault, forge state, decisions).
EOF
  fi
  log_ok "Appended UltraThink section to CLAUDE.md"
fi

# Merge hooks into settings.json (with dedup by id)
SETTINGS="$CLAUDE_DIR/settings.json"
if ! $DRY_RUN; then
  [[ -f "$SETTINGS" ]] || echo '{}' > "$SETTINGS"
fi

if $DRY_RUN; then
  log_dry "would add UltraThink hooks to $SETTINGS"
else
  cat > /tmp/ut-install-hooks.js << 'HOOKJS'
const fs = require('fs');
const settingsPath = process.argv[2];
const tier = process.argv[3];
const s = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
s.hooks = s.hooks || {};

for (const event of Object.keys(s.hooks)) {
  s.hooks[event] = (s.hooks[event] || []).filter((entry) => {
    if (!entry.id?.startsWith('ut:')) return true;
    return entry.id.startsWith('ut:adapter:');
  });
}

const add = (event, id, description, matcher, cmd, timeout) => {
  s.hooks[event] = s.hooks[event] || [];
  if (s.hooks[event].some(e => e.id === id)) return;
  const entry = { id, description, hooks: [{ type: 'command', command: cmd }] };
  if (matcher) entry.matcher = matcher;
  if (timeout) entry.hooks[0].timeout = timeout;
  s.hooks[event].push(entry);
};

const projectRoot = process.argv[4];
const cmd = (event) => `node ${projectRoot}/scripts/hook-adapter.mjs claude ${event}`;

// Manifest-backed adapter entries. The adapter applies per-hook matchers, tier gates,
// and runtime support so runtimes with fewer lifecycle events degrade by skipping.
add('SessionStart', 'ut:adapter:session-start', 'UltraThink: manifest-backed session-start hooks', null, cmd('SessionStart'), 60000);
add('PreToolUse', 'ut:adapter:pre-tool-use', 'UltraThink: manifest-backed pre-tool hooks', null, cmd('PreToolUse'), 15000);
add('PostToolUse', 'ut:adapter:post-tool-use', 'UltraThink: manifest-backed post-tool hooks', null, cmd('PostToolUse'), 60000);
add('PreCompact', 'ut:adapter:pre-compact', 'UltraThink: manifest-backed pre-compact hooks', null, cmd('PreCompact'), 15000);
add('Stop', 'ut:adapter:stop', 'UltraThink: manifest-backed stop hooks', null, cmd('Stop'), 70000);

fs.writeFileSync(settingsPath, JSON.stringify(s, null, 2) + '\n');
HOOKJS
  node /tmp/ut-install-hooks.js "$SETTINGS" "$TIER" "$ULTRA_ROOT" 2>/dev/null && log_ok "Added hooks to settings.json" || log_warn "Could not merge hooks — add manually"
  rm -f /tmp/ut-install-hooks.js
fi

# Vault templates
if $DRY_RUN; then
  log_dry "write vault templates to $VAULT_PATH/_templates/"
else
  cat > "$VAULT_PATH/_templates/memory.md" << 'EOF'
---
id: mem_{{id}}
type: memory
confidence: 0.8
importance: 5
scope: global
source: user
created: {{date}}
tags: []
---

# {{title}}

{{content}}

## Related
- [[]]
EOF

  cat > "$VAULT_PATH/_templates/decision.md" << 'EOF'
---
id: dec_{{id}}
type: decision
priority: 5
scope: global
source: user
created: {{date}}
tags: []
---

# {{title}}

{{rule}}

## Context
Why this decision was made.

## Related
- [[]]
EOF
fi

log_ok "Wrote vault templates"

# ── Step 7: Smoke test ──
log_step 8 "Running smoke test"

if $DRY_RUN; then
  log_dry "skipping smoke test in dry-run mode"
  echo ""
  log_warn "DRY RUN complete — no files were modified"
  echo ""
  exit 0
fi

ERRORS=0

# Check skills linked
linked_skills=$(find "$CLAUDE_DIR/skills" -maxdepth 1 -type l 2>/dev/null | wc -l | tr -d ' ')
if [[ "$linked_skills" -gt 0 ]]; then
  log_ok "Skills: $linked_skills linked"
else
  log_error "No skills linked"
  ((ERRORS++))
fi

# Check registry valid JSON
if jq empty "$CLAUDE_DIR/skills/_registry.json" 2>/dev/null; then
  log_ok "Registry: valid JSON"
else
  log_error "Registry: invalid JSON"
  ((ERRORS++))
fi

# Check hooks linked
linked_hooks=$(find "$CLAUDE_DIR/hooks" -name "ultrathink-*" -type l 2>/dev/null | wc -l | tr -d ' ')
if [[ "$linked_hooks" -gt 0 ]]; then
  log_ok "Hooks: $linked_hooks linked"
else
  log_error "No hooks linked"
  ((ERRORS++))
fi

# Check runner templates/config installed
if ! $NO_RUNNERS; then
  missing_runner_files=0
  missing_runner_links=0
  for file in "$CODEX_DIR/config.toml" "$CODEX_DIR/hooks.json"; do
    [[ -f "$file" ]] && grep -q "$ULTRA_ROOT" "$file" 2>/dev/null || missing_runner_files=$((missing_runner_files+1))
  done
  for link in "$CODEX_DIR/AGENTS.md" "$RUNNER_TEMPLATES_DIR/AGENTS.md" "$RUNNER_TEMPLATES_DIR/CLAUDE.md"; do
    [[ -L "$link" ]] || missing_runner_links=$((missing_runner_links+1))
  done
  if [[ "${missing_runner_files:-0}" -eq 0 && "${missing_runner_links:-0}" -eq 0 ]]; then
    log_ok "Runners: Codex/OpenAI-compatible files installed"
  else
    log_error "Runners: ${missing_runner_files:-0} generated file(s), ${missing_runner_links:-0} link(s) missing"
    ((ERRORS++))
  fi
fi

# Check vault directory
if [[ -d "$VAULT_PATH/memories" ]]; then
  log_ok "Vault: ready at $VAULT_PATH"
else
  log_error "Vault directory not created"
  ((ERRORS++))
fi

# Check DB if configured
if [[ -n "$DB_URL" ]]; then
  if cd "$ULTRA_ROOT" && timeout 5 npx tsx -e "
    const { neon } = require('@neondatabase/serverless');
    const sql = neon('$DB_URL');
    sql\`SELECT 1\`.then(() => process.exit(0)).catch(() => process.exit(1));
  " 2>/dev/null; then
    log_ok "Database: connected"
  else
    log_warn "Database: connection failed (memory will work when DB is available)"
  fi
fi

# Check config
if [[ -f "$ULTRA_DATA/config.json" ]]; then
  config_tier=$(jq -r '.tier' "$ULTRA_DATA/config.json")
  log_ok "Config: tier=$config_tier"
else
  log_error "Config not written"
  ((ERRORS++))
fi

# Core-specific checks
if [[ "$TIER" == "core" ]]; then
  if [[ -f "$ULTRA_ROOT/.env" ]] && grep -q "DATABASE_URL" "$ULTRA_ROOT/.env" 2>/dev/null; then
    log_ok "Core: .env has DATABASE_URL"
  else
    log_warn "Core: no DATABASE_URL in .env — memory/code-intel need it"
  fi
  if [[ -d "$ULTRA_ROOT/packages/code-intel" ]]; then
    log_ok "Core: code-intel present"
  fi
fi

echo ""
if [[ "$ERRORS" -eq 0 ]]; then
  echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${GREEN}${BOLD}  UltraThink $TIER_UPPER installed successfully!${NC}"
  echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
else
  echo -e "${YELLOW}${BOLD}  UltraThink installed with $ERRORS warning(s)${NC}"
fi

echo ""
echo "  Tier:       $TIER_UPPER"
echo "  Skills:     $skill_count in ~/.claude/skills/"
echo "  Hooks:      $hook_count in ~/.claude/hooks/"
echo "  References: $ref_count in ~/.claude/references/"
if ! $NO_RUNNERS; then
  echo "  Runners:    $runner_link_count links in ~/.codex/ and $RUNNER_TEMPLATES_DIR/"
fi
echo "  Vault:      $VAULT_PATH"
echo "  Config:     $ULTRA_DATA/config.json"
echo ""
echo "  Open any project directory and run 'claude' or 'codex' — UltraThink is active."
echo "  OpenAI-compatible templates are available in $RUNNER_TEMPLATES_DIR/."
if [[ -d "$VAULT_PATH" ]]; then
  echo "  Open $VAULT_PATH in Obsidian to browse your memory graph."
fi
echo ""
echo "  To update:    $0 --update"
echo "  To uninstall: $0 --uninstall"
echo ""
